parser: babel-eslint
parserOptions:
  ecmaVersion: 6,
  sourceType: module,
  ecmaFeatures:
    jsx: true
  env:
    es6: true

rules:
  semi: error
  comma-dangle: [2, always-multiline]
  no-unused-vars:
    - error
    - ignoreRestSiblings: true
